apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: "true"
objects:
- apiVersion: v1
  data:
    GITHUB_TOKEN: ${GITHUB_TOKEN}
  kind: Secret
  metadata:
    creationTimestamp: null
    name: devhub-gh-token
  type: Opaque
parameters:
- description: The github API token
  displayName: GITHUB_TOKEN
  required: true
  

